//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traineeskill
    {
        public int S_NO { get; set; }
        public string ID { get; set; }
        public string Personal_statement { get; set; }
        public string Skills { get; set; }
        public Nullable<decimal> Required_rate { get; set; }
        public string Available { get; set; }
        public string Experience { get; set; }
    }
}
